apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pharmacyvolumemanual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer

##########################################

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-my-mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: pharmacyvolumemanual
  awsElasticBlockStore:
    volumeID: vol-0f8f40a91c81d0abb
    fsType: ext4

###########################################

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size as needed
  storageClassName: pharmacyvolumemanual  # StorageClass name

############################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: pharmacy-config
data:
  .env: |
    MYSQL_HOST=my-mysql-service
    MYSQL_DATABASE=pharmacy
    MYSQL_USERNAME=root
    MYSQL_ROOT_PASSWORD=root@123

##############################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pharmacy
  template:
    metadata:
      labels:
        app: pharmacy
    spec:
      containers:
      - name: pharmacy
        image: emmanuel04/pharmacy:latest
        ports:
        - containerPort: 7000
        envFrom:
        - configMapRef:
            name: pharmacy-config

################################################

apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service
spec:
  selector:
    app: pharmacy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: NodePort
    

  

    
