apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service
spec:
  selector:
    app: pharmacy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: LoadBalancer
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pharmacy-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pharmacy-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - pharmacy-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: pharmacy-service
        port:
          number: 80

